### PR TITLE
Add test site

### PR DESCRIPTION
**Pull request by jarivankaam**

### CODE REVIEW

**Review by luttje — CHANGES_REQUESTED** [review]
Nice gradient, I like it ;)

If you could resolve the merge conflict (reject all changes except the zip files) then we can cleanly merge your .zip additions into main.

Thanks!

**Comment by jarivankaam** [comment]
I believe it should be solved

**Comment by luttje** [comment]
> I believe it should be solved

Almost, if you check the ['Files Changed'-tab](https://github.com/curio-team/info-website/pull/32/files) here with the PR. You can see there are some additional changes. 

I fixed the language in an earlier commit, this PR seems to undo those changes. Could you restore those files listed with the current main. Ideally the PR would show only changes to the two zip files.

**Comment by jarivankaam** [comment]
Not working on this pr anymore

**Pull request closed without merging**
